### ISSUE TITLE
Relative path of the ttfhe library in the guest program

### ISSUE THREAD

**Issue by weikengchen** [tremblaythibaultl/risc0-vfhe#1]
Recall that the R0 program invokes the toy TFHE library (i.e., ttfhe). 

```
[dependencies]
# If you want to try (experimental) std support, add `features = [ "std" ]` to risc0-zkvm
risc0-zkvm = { version = "0.17.0", default-features = false, features = [ "std" ] }
ttfhe = { path = "../../../ttfhe" }
```

But `../../../` will go outside of this library. Should it be `../../`? Or should a developer be advised to use the latest version of toy TFHE in https://github.com/tremblaythibaultl/ttfhe and pull himself/herself?

**Comment by tremblaythibaultl** [comment]
You're totally right, I fixed it in [bec26a6](https://github.com/tremblaythibaultl/vfhe/commit/bec26a65213733152fd3c9c0928ede5a7ec35e5e). I had already included the ttfhe code to avoid having to clone two separate repositories. 
Thanks for spotting!
